---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-unifi"
  ADDON_SLUG: "unifi"
  ADDON_TARGET: "unifi"

  ADDON_ARMV7: "false"

  ADDON_AARCH64_BASE: "hassioaddons/ubuntu-base-aarch64:2.2.0"
  ADDON_AMD64_BASE: "hassioaddons/ubuntu-base-amd64:2.2.0"
  ADDON_ARMHF_BASE: "hassioaddons/ubuntu-base-armhf:2.2.0"
  ADDON_I386_BASE: "hassioaddons/ubuntu-base-i386:2.2.0"
